[project]
name = "roguelike-tutorial-2021"
title = "Outlandish and Hazardous"
version = "0.10.0"
authors = ["Kevin Fischer"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "2.23"
edition = "pro"

[dependencies]


