[project]
name = "roguelike-tutorial-2021"
title = "Yet Another Roguelike Tutorial"
version = "0.0.1"
authors = ["Kevin Fischer"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "2.23"
edition = "pro"

[dependencies]


