AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic

# DragonRuby basic
Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - dx
    - dy
    - fg
    - bg
    - id
    - hp

Style/GlobalVars:
  AllowedVariables:
    - $gtk
    - $state
    - $terminal
    - $game
