AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic

# DragonRuby basic
Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - dx
    - dy
    - fg
    - bg
    - id
    - hp
    - to

Style/GlobalVars:
  AllowedVariables:
    - $gtk
    - $state
    - $render_context
    - $console
    - $game
    - $message_log
    - $before_each_blocks
    - $keydown_frames
